### ISSUE TITLE
Allow pre-tidying of character strings

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat.ext#12]
In the [Bayesian Modeling with RJAGS](https://github.com/datacamp/courses-bayesian-modeling-with-rjags) course, JAGS models have to be specified as a string.

This means that many students are complaining about overly strict SCTs that don't allow for variation in spacing and simple formatting differences.

I had a play around in the internals of `rjags`, but there's no obvious way of extracting a normalized or compiled model.

However, since JAGS model code is very close to R code, `formatR::tidy_source()` can be used to standardize the spacing.

```r
tidy_code <- function(x) {
  tidied <- formatR::tidy_source(
    text    = x, 
    comment = FALSE, 
    blank   = FALSE, 
    arrow   = TRUE,
    output  = FALSE
  )$text.tidy
  unlist(strsplit(tidied, "\n"))
}
```

Example usage is

```r
model_text <- "model
{
    # Likelihood model for Y[i]
    for    (i in 1: length(  Y)   ) 
{
Y[i] ~     dnorm(  m, s    ^(-2))
    }

    # Prior models for m and s
 m ~ dnorm(50, 25    ^( -2)   )
         s      ~ dunif     (0,        200)
}"

tidy_code(model_text)
## [1] "model"                           "{"                              
## [3] "    for (i in 1:length(Y)) {"    "        Y[i] ~ dnorm(m, s^(-2))"
## [5] "    }"                           "    m ~ dnorm(50, 25^(-2))"     
## [7] "    s ~ dunif(0, 200)"           "}" 
```

My current plan is to combine this with 

```r
tidy_ex_code <- function(state) {
  childState <- ChildState$new(state)
  childState$set(
    student_code = tidy_code(childState$get("student_code")),
    solution_code = tidy_code(childState$get("solution_code"))
  )
  return(invisible(childState))
}
```

in order to be able to write SCTs like

```r
ex() %>% tidy_ex_code() %>% {
  # check something
}
```

Does this sound like a sensible approach?

**Comment by richierocks** [comment]
Hmm Having re-read this, I also need some way of applying `tidy_code()` to individual variables.

**Comment by filipsch** [comment]
@richierocks It's an interesting approach, but I want you to consider another approach first before pursuing this.

I've recently added some functions that @machow started to work on a long time ago, and I finished up and documented. They use `lavaan::lavaanify` to convert the model string into a data frame that is easy to parse. You can read up on it here: 

- https://datacamp.github.io/testwhat.ext/reference/check_lavaan_df.html
- https://datacamp.github.io/testwhat.ext/reference/check_lavaan_uses.html

Also this utility function to easily check the string (which would be closer to your approach):

- https://datacamp.github.io/testwhat.ext/reference/check_lavaan_pattern.html

**Comment by machow** [comment]
This might sound crazy, but I'm pretty sure all the jags code I've ever seen is valid R syntax. I just quickly double checked by putting this in a file and parsing it in R.


test.jags

```
model
{
  # Likelihood
  for(i in 1:T) {
    y[i] ~ dnorm(mu[i], tau)
    mu[i] <- alpha[J[i]]
    # This is the clever bit - only pick out the right change point when above t_1
    J[i] <- 1 + step(t[i] - t_1)
  }

  # Priors
  alpha[1] ~ dnorm(0.0, 0.01)
  alpha[2] ~ dnorm(0.0, 0.01)
  t_1 ~ dunif(t_min, t_max)

  tau <- 1/pow(sigma, 2)
  sigma ~ dunif(0, 100)
}
```

Parsing to AST (but could use parse table with testwhat, since that's what testwhat uses?!)...

```
as.call(parse("test.jags.R"))
```

I've never seen a nice data.table representation of a jags model, but that would be awesome..

**Comment by richierocks** [comment]
The solution I opted for is to define a `sanitize_jags_model()` function in requirements.R

https://github.com/datacamp/courses-bayesian-modeling-with-rjags/blob/master/requirements.R#L17-L34

Then in the pre-exercise code I load that function.

```r
load(".sanitize_jags_model.RData") 
```

And SCTs look like this:

```r
ex() %>% 
    check_expr("sanitize_jags_model(jags_model)") %>% 
    check_result() %>% 
    check_equal(incorrect_msg = "Make sure you defined the model correctly!", append = FALSE)
```

This solves the flexibility problem around spacing and other formatting nicely.

What it doesn't do is to allow feedback messages that target specific problems in the model. So being able to traverse the parse tree would be ace. That's a lot more work though, and probably not worth it for just 1 course. If we do more RJAGS courses, we can revisit.

**Comment by richierocks** [comment]
closing since I found a workaround.
