### ISSUE TITLE
Check @import tag in roxygen

### ISSUE THREAD

**Issue by sumedh10** [datacamp/testwhat.ext#13]
Looks like `testwhat.ext` no longer exports `check_roxy_imports_package()` and `check_roxy_imports_object_from_package()`. @richierocks wrote the following SCT a while ago, but it no longer works. 

### Solution
```{r}
#' @import dplyr
#' @import purrr
#' @importFrom tidyr gather
```

### SCT
```{r}
library(testwhat.ext)
ex() %>%
   parse_roxy() %>% {
     check_roxy_imports_package(., "dplyr")
     check_roxy_imports_package(., "purrr")
     check_roxy_imports_object_from_package(., "tidyr", "gather")
  }
```

[GH](https://github.com/datacamp/courses-developing-r-packages/blob/sp-review/chapter2.md#importing-other-packages)
[Teach](https://www.datacamp.com/teach/edit/repositories/761/branches/sp-review)

Was this accidental or is this replaced by some other functions? The plan is to launch the course by EOD, Friday (Aug 24). So any help is much appreciated! 

cc @filipsch

**Comment by sumedh10** [comment]
Oops, looks like this is related to #3

**Comment by sumedh10** [comment]
Looks like I forgot to add alternative functions that do work, but it's not clear to me if they are intended to be used in this way: 

```
 ex() %>%
   parse_roxy() %>% {
     check_roxy_element_equals(., "import")
     check_roxy_element_equals(., "import", index = 2)
     check_roxy_element_equals(., "importFrom")
   }
```

**Comment by filipsch** [comment]
If you install `roxygen-fixes` branch of `testwhat.ext`, the following works:


```R
pec <- '

'

sol_code <- "
#' @import dplyr
#' @import purrr
#' @importFrom tidyr gather
x <- function(y) {
  return(NULL)
}
"

stu_code <- sol_code

library(testwhat)
setup_state(pec = pec, sol_code = sol_code, stu_code = stu_code)

library(testwhat.ext)
ex() %>%
  parse_roxy() %>% {
    check_roxy_imports_package(., "dplyr")
    check_roxy_imports_package(., "purrr")
    check_roxy_imports_object_from_package(., "tidyr", "gather")
  }

```
