### ISSUE TITLE
Reorganize @import, @importFrom fields

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat.ext#3]
`roxygen2:::parse_blocks()` imports these in a weird format that makes tests hard to write. 

`@import` ought to become a character vector of package names.

`@importFrom` ought to become a list of character vectors. The names of the elements ought to be packages, and the character vectors ought to be names of objects imported from those packages.

**Comment by filipsch** [comment]
This seems to be in shape on the `roxygen-fixes` branch:

```R
sol_code <- "
#' @import dplyr
#' @import purrr
#' @importFrom tidyr gather
x <- function(y) {
  return(NULL)
}
"

stu_code <- sol_code

library(testwhat)
setup_state(pec = '', sol_code = sol_code, stu_code = stu_code)

library(testwhat.ext)
x <- ex() %>%
  parse_roxy()
```

The format is now as Richie suggested:

```
> x$get("student_pd")[[1]][["import"]]
[1] "dplyr" "purrr"
> 
> x$get("student_pd")[[1]][["importFrom"]]
$tidyr
[1] "gather"
```
