### ISSUE TITLE
Prevent roxygen2 trying to find the DESCRIPTION file

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat.ext#5]
If the object being parsed has the value `"_PACKAGE"`, then `roxygen2:::parse_blocks()` goes hunting for the DESCRIPTION file, which in this case doesn't exist.

Find some way to turn this behavior off!

**Comment by richierocks** [comment]
Easiest fix is to add

```r
lines <- sub("\n['\"]_PACKAGE['\"]\n", "\nNULL\n", lines)
```

before parsing.

**Comment by sumedh10** [comment]
@richierocks @filipsch 

This is one of the blockers for launching Developing R Packages course (scheduled Aug 24).



### PEC
```{r}
library(devtools)
download.file("http://s3.amazonaws.com/assets.datacamp.com/production/repositories/761/datasets/2b4a9cf769512297a8bbc1fb363681fc57b84e94/ch2_ex13.zip", destfile = "file.zip")
unzip("file.zip")
unlink("file.zip", recursive = TRUE)
unlink("__MACOSX", recursive = TRUE)
setwd("datasummary")
```


### Solution
```{r}
#' datasummary: Custom Data Summaries
#'
#' Easily generate custom data frame summaries
#'
#' @docType package
#' @name datasummary
"_PACKAGE"
```

### SCT
```{r}
library(testwhat.ext)
ex() %>%
   parse_roxy() %>% {
     check_roxy_element_matches(., "title", "Custom Data Summaries", fixed = TRUE)
     check_roxy_element_matches(., "description", "Easily generate custom data frame summaries", fixed = TRUE)
     check_roxy_element_matches(., "docType", "package", fixed = TRUE)
     check_roxy_element_matches(., "name", "datasummary", fixed = TRUE)
   }
```


### Error

> DataCamp encountered the following error during submit:
Error in read.dcf(file, keep.white = "Authors@R"): cannot open the connection



The solution passes without the SCT. 


[GH](https://github.com/datacamp/courses-developing-r-packages/blob/sp-review/chapter2.md#adding-package-documentation)
[Teach ](https://www.datacamp.com/teach/edit/repositories/761/branches/sp-review)

**Comment by filipsch** [comment]
I verified, and this works on `roxygen-fixes`.
